name = "simple-bill-worker"
main = "src/index.js"
compatibility_date = "2023-12-18"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BILL_KV"
id = "b5f8a23e7d06c2de5ef515ae93e16016"

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"

# wrangler.toml
name = 'bill'