name = "bill"
main = "src/index.js"
compatibility_date = "2023-12-18"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BILL_KV"
id = "1f02baeb34aa482d93f2acc7caaa407e"

[site]
bucket = "./dist"