name = "simple-bill-worker"
main = "src/index.js"
compatibility_date = "2023-12-18"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BILL_KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"
