name = "simple-bill-worker"
main = "src/index.js"
compatibility_date = "2023-12-18"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "Bill_kv"
id = "1f02baeb34aa482d93f2acc7caaa407e"

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"

# wrangler.toml
name = 'bill'